flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- async-2.1.0
- fgl-5.5.2.3
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- mtl-2.2.1
- parsec-3.1.11
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- readline-1.0.3.0
- setenv-0.1.1.3
- stm-2.4.4.1
- text-1.2.2.1
- tf-random-0.5
resolver: ghc-7.10.2
